/* Generated by Together */

#include <excp.h>
#include <DataSocket.h>
#include "GroupServerApp.h"
#include "Player.h"
#include "Team.h"
#include <GameCommon.h>

_DBC_USING

Player::Player(uLong size)
:PreAllocStru(size),m_gate(0),m_gtAddr(0),m_refuse_sess(false),m_refuse_tome(false)
{
	m_mtxCha.Create(false);
}

Player::~Player()
{
}
void Player::Initially()
{
	RunBiDirectItem<Player>::Initially();
	GuildMember::Initially();
	TeamMember::Initially();
	//ToDo:Self's Init Operation

	m_lastip[0]		=1;
	m_lastreason[0]	=1;
	m_lastleavetime[0] =1;
	m_pingply		=0;

	m_gm		=0;
	m_gate		=0;
	m_gtAddr	=0;
	m_bp_currcha=-1;
	m_currcha	=-1;
	m_chanum	=0;
	m_acctid	=0;
	m_acctLoginID = 0;
	m_acctname.clear();
	m_chatnum	=0;
	m_chatarranum	=0;

	m_bWG = false;
	m_bCheat = false;

	m_lChatMoney = 1000;
	m_lTradeChatMoney = 1000;
	m_bNew = false;

	EndPlayReset();
}
void Player::Finally()
{
	m_gate		=0;
	m_gtAddr	=0;
	m_bp_currcha=-1;
	m_currcha	=-1;
	m_chanum	=0;
	m_acctid	=0;
	m_acctLoginID = 0;
	// Request deallocation of memory used by std::string
	m_acctname.clear();
	m_acctname.shrink_to_fit();
	m_password.clear();
	m_password.shrink_to_fit();
	m_passport.clear();
	m_passport.shrink_to_fit();
	for(int i = 0; i < emMaxCharacters; i++)
	{
	  m_chaname[i].clear();
	  m_chaname[i].shrink_to_fit();
	  m_motto[i].clear();
	  m_motto[i].shrink_to_fit();
	}
	m_chatnum	=0;
	m_chatarranum	=0;

	m_lChatMoney = 1000;
	m_lTradeChatMoney = 1000;
	m_bNew = false;

	//-----------
	TeamMember::Finally();
	GuildMember::Finally();
	RunBiDirectItem<Player>::Finally();
}
bool Player::BeginRun()
{
	return	RunBiDirectItem<Player>::_BeginRun(&(g_gpsvr->m_plylst))?true:false;
}
bool Player::EndRun()
{
	return RunBiDirectItem<Player>::_EndRun()?true:false;
}
void Player::EndPlay(DataSocket* datasock) {

	if (m_currcha >= 0) {
		// g_gpsvr->DelPlayerFromList(m_chaid[m_currcha]);

		CountEstopTime();
		if (GetTeam()) {
			RPacket l_rpk1;
			g_gpsvr->CP_TEAM_LEAVE(this, datasock, l_rpk1);
		}
		if (m_chatarranum) {
			WPacket l_wpk1 = g_gpsvr->GetWPacket();
			MutexArmor selock(m_mtxChat);
			while (m_chatarranum) {
				WPacket l_wpk2 = l_wpk1; // error here (calls WPacket operator=)
				l_wpk2.WriteLong(m_chat[0]->GetSession()->GetID());
				auto packetx = RPacket(l_wpk2);
				g_gpsvr->CP_SESS_LEAVE(this, datasock, packetx);
			}
			selock.unlock();
		}
		if (GetGuild()) {
			WPacket l_toGuild = g_gpsvr->GetWPacket();
			l_toGuild.WriteCmd(CMD_PC_GUILD);
			l_toGuild.WriteChar(MSG_GUILD_OFFLINE);
			l_toGuild.WriteLong(m_chaid[m_currcha]);

			Player* l_plylst[10240]{};
			short l_plynum = 0;

			RunChainGetArmor<GuildMember> l(*GetGuild());
			Player* l_ply;
			while (l_ply = static_cast<Player*>(GetGuild()->GetNextItem())) {
				if (l_ply != this) {
					l_plylst[l_plynum] = l_ply;
					l_plynum++;
				}
			}
			l.unlock();
			g_gpsvr->SendToClient(l_plylst, l_plynum, l_toGuild);
			LeaveGuild();
		}
		{
			MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
			g_gpsvr->m_tblcharaters->SetAddr(m_chaid[m_currcha], 0);
			--(g_gpsvr->m_curChaNum);

			// Friends offline notification
			{
				friend_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblX1->get_friend_dat(l_farray, l_num, m_chaid[m_currcha]);

				WPacket l_toFrnd = g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_FRND_REFRESH);
				l_toFrnd.WriteChar(MSG_FRND_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player* l_plylst[10240]{};
				short l_plynum = 0;

				Player* l_ply1;
				char l_currcha;
				// l_ply1->m_gtAddr;

				for (int i = 0; i < l_num; i++) {

					if (l_farray[i].cha_id && (l_ply1 = static_cast<Player*>(MakePointer(l_farray[i].memaddr))) // crash here with offline stall //mothannakh//fixed
						&& ((l_currcha = l_ply1->m_currcha) >= 0) && (l_ply1->m_chaid[l_currcha] == l_farray[i].cha_id)) {
						// if start
						l_plylst[l_plynum] = l_ply1;
						l_plynum++;

					} // if end
				}

				g_gpsvr->SendToClient(l_plylst, l_plynum, l_toFrnd);
			}

			{
				TBLMaster::master_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblmaster->GetMasterData(l_farray,l_num,m_chaid[m_currcha]);

				WPacket	l_toFrnd =g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_MASTER_REFRESH);
				l_toFrnd.WriteChar(MSG_PRENTICE_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player *l_plylst[10240];
				short	l_plynum	=0;

				Player	*	l_ply1;char	l_currcha;
				for(int i=0;i<l_num;i++)
				{
					if(l_farray[i].cha_id
						&&(l_ply1 =(Player*)MakePointer(l_farray[i].memaddr)) //crash here with offline stall //mothannakh	fixed
						&&((l_currcha =l_ply1->m_currcha)>=0)
						&&(l_ply1->m_chaid[l_currcha] ==l_farray[i].cha_id))
					{
						l_plylst[l_plynum]	=l_ply1;
						l_plynum++;
					}
				}
				g_gpsvr->SendToClient(l_plylst,l_plynum,l_toFrnd);
				m_CurrMasterNum = 0;
			}

			{
				TBLMaster::master_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblmaster->GetPrenticeData(l_farray,l_num,m_chaid[m_currcha]);

				WPacket	l_toFrnd =g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_MASTER_REFRESH);
				l_toFrnd.WriteChar(MSG_MASTER_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player *l_plylst[10240];
				short	l_plynum	=0;

				Player	*	l_ply1;char	l_currcha;
				for(int i=0;i<l_num;i++)
				{
					if(l_farray[i].cha_id
						&&(l_ply1 =(Player*)MakePointer(l_farray[i].memaddr))	//crash here with offline stall //mothannakh	fixed
						&&((l_currcha =l_ply1->m_currcha)>=0)
						&&(l_ply1->m_chaid[l_currcha] ==l_farray[i].cha_id))
					{
						l_plylst[l_plynum]	=l_ply1;
						l_plynum++;
					}
				}
				g_gpsvr->SendToClient(l_plylst,l_plynum,l_toFrnd);
				m_CurrPrenticeNum = 0;
			}
			
			// mothannakh disable mentor/master notices

			l_lockDB.unlock();
		}

	}
}

void Player::EndPlayReset()
{
	m_refuse_tome	=false;
	m_refuse_sess	=false;
	m_worldtick	=0;
	m_tradetick	=0;
	m_worldticktemp = 0;
	m_tradeticktemp = 0;
	m_toyoutick	=0;
}

char Player::FindIndexByChaName(cChar *chaname)
{
	if(!chaname)return -1;
	char i=0;
	for( i=0;i<m_chanum;i++)
	{
		if(m_chaname[i] ==chaname)
			break;
	}
	if(i<m_chanum)
	{
		return i;
	}else
	{
		return -1;
	}
}
void Player::SendSysInfo(cChar	*info)
{
	if(m_currcha <0 || !m_gate ||!m_gate->GetDataSock())return;
	WPacket l_wpk	=m_gate->GetDataSock()->GetWPacket();
	l_wpk.WriteCmd(CMD_MC_SYSINFO);
	l_wpk.WriteString(info);
	g_gpsvr->SendToClient(this,l_wpk);
}

extern BOOL GetOnlineCount( DWORD& dwLoginNum, DWORD& dwPlayerNum );

void Player::DoCommand(cChar *cmd)
{
	if((!strcmp(cmd ,"getlastconnection"))
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"getlastconnection"))
	{
		MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
		if(m_lastip[0] ==1)
		{
			g_gpsvr->m_tblaccounts->FetchRowByActID(m_acctid);
			//strcpy(m_lastip,g_gpsvr->m_tblaccounts->GetLast_IP());
			strncpy_s(m_lastip,sizeof(m_lastip),g_gpsvr->m_tblaccounts->GetLast_IP(),_TRUNCATE);

			//strcpy(m_lastreason,g_gpsvr->m_tblaccounts->GetDisc_Reason());
			strncpy_s(m_lastreason,sizeof(m_lastreason),g_gpsvr->m_tblaccounts->GetDisc_Reason(),_TRUNCATE);

			//strcpy(m_lastleavetime,g_gpsvr->m_tblaccounts->GetLast_Leave());
			strncpy_s(m_lastleavetime,sizeof(m_lastleavetime),g_gpsvr->m_tblaccounts->GetLast_Leave(),_TRUNCATE);

		}
		l_lockDB.unlock();
		//SendSysInfo(dstring("ÉÏ´ÎµÇÂ¼IP:")<<m_lastip<<";ÉÏ´Î¶Ï¿ªÁ¬½ÓµÄÊ±¼ä/Ô­Òò:"<<m_lastleavetime<<"/"<<m_lastreason);
		char l_buf[512];
		//sprintf(l_buf,RES_STRING(GP_PLAYER_CPP_00001),m_lastip,m_lastleavetime,m_lastreason);
		//_snprintf_s(l_buf,sizeof(l_buf),_TRUNCATE,RES_STRING(GP_PLAYER_CPP_00001),m_lastip,m_lastleavetime,m_lastreason);
		CFormatParameter param(3);
		param.setString( 0, m_lastip );
		param.setString( 1, m_lastleavetime );
		param.setString( 2, m_lastreason );
		RES_FORMAT_STRING( GP_PLAYER_CPP_00001, param, l_buf );
		SendSysInfo(l_buf);
	}else if((!strncmp(cmd,"getuserconnection ",strlen("getuserconnection ")))
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"getuserconnection"))
	{
		Player	*l_ply	=g_gpsvr->FindPlayerByChaName(cmd +strlen("getuserconnection "));
		if(!l_ply)
		{
			//SendSysInfo(dstring("Íæ¼Ò¡¾")<<cmd +strlen("getuserconnection ") <<"¡¿µ±Ç°²»ÔÚÏßÉÏ");
			char l_buf[512];
			//sprintf(l_buf,RES_STRING(GP_PLAYER_CPP_00002),cmd +strlen("getuserconnection "));
			_snprintf_s(l_buf,sizeof(l_buf),_TRUNCATE,RES_STRING(GP_PLAYER_CPP_00002),cmd +strlen("getuserconnection "));
			SendSysInfo(l_buf);
		}else
		{
			MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
			if(l_ply ->m_lastip[0] ==1)
			{
				g_gpsvr->m_tblaccounts->FetchRowByActID(l_ply->m_acctid);
				//strcpy(l_ply->m_lastip,g_gpsvr->m_tblaccounts->GetLast_IP());
				strncpy_s(l_ply->m_lastip,sizeof(l_ply->m_lastip),g_gpsvr->m_tblaccounts->GetLast_IP(),_TRUNCATE);

				//strcpy(l_ply->m_lastreason,g_gpsvr->m_tblaccounts->GetDisc_Reason());
				strncpy_s(l_ply->m_lastreason,sizeof(l_ply->m_lastreason),g_gpsvr->m_tblaccounts->GetDisc_Reason(),_TRUNCATE);

				//strcpy(l_ply->m_lastleavetime,g_gpsvr->m_tblaccounts->GetLast_Leave());
				strncpy_s(l_ply->m_lastleavetime,sizeof(l_ply->m_lastleavetime),g_gpsvr->m_tblaccounts->GetLast_Leave(),_TRUNCATE);

			}
			l_lockDB.unlock();
			//SendSysInfo(dstring("¡¾")<<cmd +strlen("getuserconnection ")<<"¡¿ÉÏ´ÎµÇÂ¼IP:"<<l_ply->m_lastip<<";ÉÏ´Î¶Ï¿ªÁ¬½ÓµÄÊ±¼ä/Ô­Òò:"<<l_ply->m_lastleavetime<<"/"<<l_ply->m_lastreason);
			char l_buf[512];
			//sprintf(l_buf,RES_STRING(GP_PLAYER_CPP_00003),cmd +strlen("getuserconnection "), l_ply->m_lastip,l_ply->m_lastleavetime,l_ply->m_lastreason);
			//_snprintf_s(l_buf,sizeof(l_buf),_TRUNCATE,RES_STRING(GP_PLAYER_CPP_00003),cmd +strlen("getuserconnection "), l_ply->m_lastip,l_ply->m_lastleavetime,l_ply->m_lastreason);
			CFormatParameter param(4);
			param.setString( 0, cmd +strlen("getuserconnection ") );
			param.setString( 1, l_ply->m_lastip );
			param.setString( 2, l_ply->m_lastleavetime );
			param.setString( 3, l_ply->m_lastreason );
			RES_FORMAT_STRING( GP_PLAYER_CPP_00003, param, l_buf );
			SendSysInfo(l_buf);
		}
	}else if((!strcmp(cmd ,"getusernum+"))&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"getusernum+"))
	{	
		//// add by ning.yan 20081024 GM²ÅÓÐ²é¿´ÈËÊýÈ¨ÏÞ begin
		//if( !this->m_gm ) 
		//{
		//	//SendSysInfo( "ÄãÃ»ÓÐÈ¨ÏÞ£¡" );
		//	SendSysInfo( RES_STRING(GP_PLAYER_CPP_00011) );
		//	return;
		//}// end

		Player	*l_ply	=g_gpsvr->FindPlayerByChaName(m_chaname[m_currcha].c_str());

		if(l_ply)
		{
			if(l_ply->m_gm > 0)
			{
				MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
				DWORD dwLoginNum = DWORD(g_gpsvr->m_plylst.GetTotal());
				DWORD dwPlayerNum  = DWORD(g_gpsvr->m_curChaNum);
				if( GetOnlineCount( dwLoginNum, dwPlayerNum ) )
				{
					//SendSysInfo(dstring("µ±Ç°µÇÂ¼/ÓÎÏ·Íæ¼ÒÊý£º")<<dwLoginNum<<"/"<<dwPlayerNum);
					char l_buf[512];
					//sprintf(l_buf,RES_STRING(GP_PLAYER_CPP_00004),dwLoginNum,dwPlayerNum);
					//_snprintf_s(l_buf,sizeof(l_buf),_TRUNCATE,RES_STRING(GP_PLAYER_CPP_00004),dwLoginNum,dwPlayerNum);
					CFormatParameter param(2);
					param.setLong( 0, dwLoginNum );
					param.setLong( 1, dwPlayerNum );
					RES_FORMAT_STRING( GP_PLAYER_CPP_00004, param, l_buf );
					SendSysInfo(l_buf);
				}
			}
		}
	}else if((!strncmp(cmd ,"ping ",strlen("ping ")))
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"ping"))
	{
		Player	*l_ply	=g_gpsvr->FindPlayerByChaName(cmd +strlen("ping "));
		if(!l_ply)
		{
			//SendSysInfo(dstring("Íæ¼Ò¡¾")<<cmd +strlen("ping ") <<"¡¿µ±Ç°²»ÔÚÏßÉÏ");
			char l_buf[512];
			//sprintf(l_buf,RES_STRING(GP_PLAYER_CPP_00005),cmd +strlen("ping "));
			_snprintf_s(l_buf,sizeof(l_buf),_TRUNCATE,RES_STRING(GP_PLAYER_CPP_00005),cmd +strlen("ping "));
			SendSysInfo(l_buf);
		}else
		{
			l_ply->m_pingply	=this;

			WPacket	l_wpk		=g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_PC_PING);
			g_gpsvr->SendToClient(l_ply,l_wpk);
		}
	}else if((!strncmp(cmd,"bbs ",strlen("bbs ")))
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"bbs"))
	{
		//if(m_gm)
		//{
			char	*	l_dim;
			cChar	*	l_cmd	=cmd+strlen("bbs ");
			l_dim	=(char*)strchr(l_cmd,',');
			//if(!l_dim)SendSysInfo("bbs¸ñÊ½:@@ bbs [¼ä¸ô¡Á10Ãë],[´ÎÊý],[ÄÚÈÝ]");
			if(!l_dim)SendSysInfo(RES_STRING(GP_PLAYER_CPP_00006));
			*l_dim=0;
			uLong	l_inter	=atoi(l_cmd);
			//if(!l_inter)SendSysInfo("¼ä¸ô±ØÐë>1");
			if(!l_inter)SendSysInfo(RES_STRING(GP_PLAYER_CPP_00007));
			l_cmd	=l_dim+1;
			l_dim	=(char*)strchr(l_cmd,',');
			//if(!l_dim)SendSysInfo("bbs¸ñÊ½:@@ bbs [¼ä¸ô¡Á10Ãë],[´ÎÊý],[ÄÚÈÝ]");
			if(!l_dim)SendSysInfo(RES_STRING(GP_PLAYER_CPP_00006));
			*l_dim=0;
			uLong	l_times	=atoi(l_cmd);
			//if(!l_times)SendSysInfo("´ÎÊý±ØÐë>1");
			if(!l_times)SendSysInfo(RES_STRING(GP_PLAYER_CPP_00008));
			l_cmd	=l_dim+1;
			//if(!strlen(l_cmd))SendSysInfo("ÄÚÈÝ³¤¶È±ØÐë>0");
			if(!strlen(l_cmd))SendSysInfo(RES_STRING(GP_PLAYER_CPP_00009));

			g_gmbbs->AddBBS(l_inter,l_times,l_cmd);
		//}else
		//{
			//SendSysInfo("È¨ÏÞ²»×ã¡£");
		//	SendSysInfo(RES_STRING(GP_PLAYER_CPP_00010));
		//}
	}else if( (!strncmp( cmd, "estop", strlen("estop") ) )
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"estop"))
	{
		// ½ûÑÔÍæ¼Ò
		//if( !this->m_gm ) 
		//{
		//	//SendSysInfo( "ÄãÃ»ÓÐÈ¨ÏÞ£¡" );
		//	SendSysInfo( RES_STRING(GP_PLAYER_CPP_00011) );
		//	return;
		//}

		cChar* l_cmd = cmd + strlen( "estop" );
		l_cmd = strchr( l_cmd, ' ' );
		//if( !l_cmd ) SendSysInfo( "½ûÑÔ¸ñÊ½£º@@ estop [±»½ûÑÔ½ÇÉ«Ãû³Æ],[½ûÑÔÊ±¼ä£¨µ¥Î»·ÖÖÓ£©]" );
		if( !l_cmd ) SendSysInfo( RES_STRING(GP_PLAYER_CPP_00012) );
		cChar* l_plyname = ++l_cmd;
		l_cmd = strchr( l_cmd, ',' );
		//if( !l_cmd ) SendSysInfo( "½ûÑÔ¸ñÊ½£º@@ estop [±»½ûÑÔ½ÇÉ«Ãû³Æ],[½ûÑÔÊ±¼ä£¨µ¥Î»·ÖÖÓ£©]" );
		if( !l_cmd ) SendSysInfo( RES_STRING(GP_PLAYER_CPP_00012)  );
		*const_cast<char*>(l_cmd) = 0;
		uLong lTimes = atoi( ++l_cmd );
		EstopPlayer( l_plyname, lTimes );
		
	}else if( (!strncmp( cmd, "delestop", strlen( "delestop" ) ) )
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"delestop"))
	{		
		//// ½ûÑÔÍæ¼Ò
		//if( !this->m_gm ) 
		//{
		//	//SendSysInfo( "ÄãÃ»ÓÐÈ¨ÏÞ£¡" );
		//	SendSysInfo(RES_STRING(GP_PLAYER_CPP_00011) );
		//	return;
		//}

		cChar* l_cmd = cmd + strlen( "estop" );
		l_cmd = strchr( l_cmd, ' ' );
		//if( !l_cmd ) SendSysInfo( "½â³ý½ûÑÔ¸ñÊ½£º@@ delestop [±»½ûÑÔ½ÇÉ«Ãû³Æ]" );
		if( !l_cmd ) SendSysInfo( RES_STRING(GP_PLAYER_CPP_00013) );
		cChar* l_plyname = ++l_cmd;
		DelEstopPlayer( l_plyname );

	}else if( (!strncmp( cmd, "disable", strlen("disable") ) )
		&& PrivilegeCheck::Instance()->HasPrivilege(this->m_gm,"disable"))
	{
		//if( !this->m_gm ) 
		//{
		//	//SendSysInfo( "ÄãÃ»ÓÐÈ¨ÏÞ£¡" );
		//	SendSysInfo(RES_STRING(GP_PLAYER_CPP_00011));
		//	return;
		//}

		// ÆÁ±Î¸Ã½ÇÉ«ÕÊºÅ
		cChar* l_cmd = cmd + strlen( "estop" );
		l_cmd = strchr( l_cmd, ' ' );
		//if( !l_cmd ) SendSysInfo( "ÆÁ±Î½ÇÉ«ÕÊºÅ¸ñÊ½£º@@ disable [±»ÆÁ±Î½ÇÉ«Ãû³Æ]" );
		if( !l_cmd ) SendSysInfo( RES_STRING(GP_PLAYER_CPP_00014) );
		cChar* l_plyname = ++l_cmd;
		l_cmd = strchr( l_cmd, ',' );
		//if( !l_cmd ) SendSysInfo( "ÆÁ±Î½ÇÉ«ÕÊºÅ¸ñÊ½£º@@ disable [±»ÆÁ±Î½ÇÉ«Ãû³Æ]" );
		if( !l_cmd ) SendSysInfo( RES_STRING(GP_PLAYER_CPP_00014) );
		*const_cast<char*>(l_cmd) = 0;
		uLong lTimes = atoi( ++l_cmd );
		DisablePlayer( l_plyname, lTimes );
		
	}else
	{
		//SendSysInfo("²»Ö§³ÖµÄÃüÁî¡£");
		SendSysInfo(RES_STRING(GP_PLAYER_CPP_00015));
		return ;
	}
}

bool Player::IsEstop()
{
	if( !m_estop[m_currcha] ) return false;
	uLong	l_curtick	=g_gpsvr->GetCurrentTick();
	if( l_curtick - this->m_worldtick > 1000*60*2 )
	{
		MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
		if( !g_gpsvr->m_tblcharaters->IsEstop( m_chaid[m_currcha] ) )
		{
			// ·¢ËÍ½â³ýÃüÁî
			WPacket l_wpk	=g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_PT_DEL_ESTOPUSER);
			g_gpsvr->SendToClient(this,l_wpk);

			//SendSysInfo( "½ûÑÔÒÑ±»½â³ý£¡" );
			SendSysInfo( RES_STRING(GP_PLAYER_CPP_00016) );

			CountEstopTime();
			m_estop[m_currcha] = false;			
			return false;
		}
		else
		{
			m_estop[m_currcha] = true;
			return true;
		}
	}
	return true;
}

void Player::CheckEstop()
{
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	g_gpsvr->m_tblcharaters->StartEstopTime( m_chaid[m_currcha] );
	if( g_gpsvr->m_tblcharaters->IsEstop( m_chaid[m_currcha] ) )
	{
		// ·¢ËÍ½ûÑÔÏûÏ¢ºÍÃüÁî
		WPacket l_wpk	=g_gpsvr->GetWPacket();
		l_wpk.WriteCmd(CMD_PT_ESTOPUSER);
		g_gpsvr->SendToClient(this,l_wpk);

		//SendSysInfo( "ÄãÒÑ¾­±»ÏµÍ³½ûÑÔ£¡" );
		SendSysInfo( RES_STRING(GP_PLAYER_CPP_00017) );

		m_estop[m_currcha] = true;
		m_worldtick = g_gpsvr->GetCurrentTick();
	}
}

void Player::CountEstopTime()
{
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if( m_estop[m_currcha] ) g_gpsvr->m_tblcharaters->EndEstopTime( m_chaid[m_currcha] );
}

void Player::DelEstopPlayer( cChar* plyname )
{
	Player* ply = g_gpsvr->FindPlayerByChaName( plyname );
	if( ply )
	{
		// ½ÇÉ«ÔÚÏß½ûÑÔ
		ply->m_estop[ply->m_currcha] = false;
	}

	// Êý¾Ý¿â²Ù×÷
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if( !g_gpsvr->m_tblcharaters->DelEstop( plyname ) )
	{
		char szData[128];
		//sprintf( szData, "½â³ý½ûÑÔ½ÇÉ«¡¶%s¡·²»´æÔÚ£¡", plyname );
		//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00018), plyname );
		_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00018), plyname );
		SendSysInfo( szData );
		return;
	}
	else
	{
		char szData[128];
		//sprintf( szData, "½â³ý½ÇÉ«¡¶%s¡·½ûÑÔ²Ù×÷³É¹¦£¡", plyname );
		//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00019), plyname );
		_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00019), plyname );
		SendSysInfo( szData );

		char szTemp[128];
		//sprintf( szTemp, "ÄãÒÑ¾­±»GM¡¶%s¡·½â³ý½ûÑÔ£¡", m_chaname[m_currcha].c_str() );
		//sprintf( szTemp, RES_STRING(GP_PLAYER_CPP_00020), m_chaname[m_currcha].c_str() );
		_snprintf_s( szTemp,sizeof(szTemp),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00020), m_chaname[m_currcha].c_str() );
		ply->SendSysInfo( szTemp );

		// ·¢ËÍ½ûÑÔÃüÁî
		WPacket l_wpk	=g_gpsvr->GetWPacket();
		l_wpk.WriteCmd(CMD_PT_DEL_ESTOPUSER);
		g_gpsvr->SendToClient(ply,l_wpk);

		LogLine l_line(g_LogGrpServer);
		//l_line<<newln<<"½ÇÉ«["<<m_chaname[m_currcha]<<"]½â³ý½ûÑÔplyname:["<<ply->m_chaname[ply->m_currcha]<<"]"<<endln;
		l_line<<newln<<"char["<<m_chaname[m_currcha]<<"]may speak plyname:["<<ply->m_chaname[ply->m_currcha]<<"]"<<endln;
	}
}

void Player::EstopPlayer( cChar* plyname, uLong lTimes )
{
	Player* ply = g_gpsvr->FindPlayerByChaName( plyname );
	if( ply )
	{
		// ½ÇÉ«ÔÚÏß½ûÑÔ
		ply->m_estop[ply->m_currcha] = true;
	}
	
	// Êý¾Ý¿â²Ù×÷
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if( !g_gpsvr->m_tblcharaters->Estop( plyname, lTimes ) )
	{
		char szData[128];
		//sprintf( szData, "½ûÑÔ½ÇÉ«¡¶%s¡·²»´æÔÚ£¡", plyname );
		//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00023), plyname );
		_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00023), plyname );
		SendSysInfo( szData );
		return;
	}
	else
	{
		char szData[128];
		//sprintf( szData, "½ûÑÔ½ÇÉ«¡¶%s¡·%d·ÖÖÓ²Ù×÷³É¹¦£¡", plyname, lTimes );
		//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00024), plyname, lTimes );
		//_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00024), plyname, lTimes );
		CFormatParameter param(2);
		param.setString( 0, plyname );
		param.setLong( 1, lTimes );
		RES_FORMAT_STRING( GP_PLAYER_CPP_00024, param, szData );
		SendSysInfo( szData );

		char szTemp[128];
		//sprintf( szTemp, "Äã±»GM½ÇÉ«¡¶%s¡·½ûÑÔ%d·ÖÖÓ£¡", m_chaname[m_currcha].c_str(), lTimes );
		//sprintf( szTemp, RES_STRING(GP_PLAYER_CPP_00025), m_chaname[m_currcha].c_str(), lTimes );
		//_snprintf_s( szTemp,sizeof(szTemp),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00025), m_chaname[m_currcha].c_str(), lTimes );
		CFormatParameter paramTemp(2);
		paramTemp.setString( 0, m_chaname[m_currcha].c_str() );
		paramTemp.setLong( 1, lTimes );
		RES_FORMAT_STRING( GP_PLAYER_CPP_00025, paramTemp, szTemp );
		ply->SendSysInfo( szTemp );

		// ·¢ËÍ½ûÑÔÃüÁî
		WPacket l_wpk	=g_gpsvr->GetWPacket();
		l_wpk.WriteCmd(CMD_PT_ESTOPUSER);
		g_gpsvr->SendToClient(ply,l_wpk);

		LogLine l_line(g_LogGrpServer);
		//l_line<<newln<<"½ÇÉ«["<<m_chaname[m_currcha]<<"]½ûÑÔplyname:["<<ply->m_chaname[ply->m_currcha]<<"]"<<lTimes<<"·ÖÖÓ"<<endln;
		l_line<<newln<<"char ["<<m_chaname[m_currcha]<<"] can't speack plyname:["<<ply->m_chaname[ply->m_currcha]<<"]"<<lTimes<<"minute"<<endln;
	}
}

void Player::DisablePlayer( cChar* plyname, uLong lTimes )
{
	// ÆÁ±Î½ÇÉ«
	Player* ply = g_gpsvr->FindPlayerByChaName( plyname );
	if( ply )
	{
		ply->EndPlay(m_gate->GetDataSock());
		if(ply->EndRun())
		{
			//ÏòAccountServer·¢ËÍDisableÃüÁî
			WPacket l_wpk	=g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_PA_USER_DISABLE);
			l_wpk.WriteLong(ply->m_acctLoginID);
			l_wpk.WriteLong(lTimes);
			g_gpsvr->SendData(g_gpsvr->m_acctsock,l_wpk);
			
			//ÏòGateServer·¢ËÍÌßÈËÃüÁî
			l_wpk	=g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_AP_KICKUSER);
			g_gpsvr->SendToClient(ply,l_wpk);

			char szData[128];
			//sprintf( szData, "ÆÁ±Î½ÇÉ«¡¶%s¡·ÕÊºÅ²Ù×÷³É¹¦£¡", plyname );
			//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00028), plyname );
			_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00028), plyname );
			SendSysInfo( szData );

			//ÌßÈË³É¹¦
			LogLine l_line(g_LogGrpServer);
			//l_line<<newln<<"ÆÁ±Îµôacctid/acctname:["<<ply->m_acctid<<"]/["<<ply->m_acctname<<"],²¢ÇÒ½«Íæ¼Ò½ÇÉ«ÌßÏÂÏß!"<<endln;
			l_line<<newln<<"screen acctid/acctname:["<<ply->m_acctid<<"]/["<<ply->m_acctname<<"],kill the player!"<<endln;
		}
		ply->Free();
	}
	else
	{
		int cha_accid;
		if( !g_gpsvr->m_tblcharaters->FetchAccidByChaName( plyname, cha_accid ) )
		{
			char szData[128];
			//sprintf( szData, "ÆÁ±Î½ÇÉ«¡¶%s¡·²»´æÔÚ£¡", plyname );
			//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00031), plyname );
			_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00031), plyname );
			SendSysInfo( szData );
			return;
		}
		else
		{
			//ÏòAccountServer·¢ËÍDisableÃüÁî
			WPacket l_wpk	=g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_PA_USER_DISABLE);
			l_wpk.WriteLong(m_acctLoginID);			
			l_wpk.WriteLong(lTimes);
			g_gpsvr->SendData(g_gpsvr->m_acctsock,l_wpk);

			char szData[128];
			//sprintf( szData, "ÆÁ±Î½ÇÉ«¡¶%s¡·ÕÊºÅ²Ù×÷³É¹¦£¡", plyname );
			//sprintf( szData, RES_STRING(GP_PLAYER_CPP_00032), plyname );
			_snprintf_s( szData,sizeof(szData),_TRUNCATE, RES_STRING(GP_PLAYER_CPP_00032), plyname );
			SendSysInfo( szData );

			//ÌßÈË³É¹¦
			LogLine l_line(g_LogGrpServer);
			//l_line<<newln<<"ÊÕµ½Ò»¸öÆÁ±Îµôacctid/plyname:["<<cha_accid<<"]/["<<plyname<<"]µÄÃüÁî!"<<endln;
			l_line<<newln<<"recieve screen acctid/plyname:["<<cha_accid<<"]/["<<plyname<<"]command!"<<endln;
		}
	}	
}